export const inputConstant={
	INPUT_SEARCH:"INPUT_SEARCH",
	INPUT_TEXT_BOX:"INPUT_TEXT_BOX",
	DROP_DOWN_LIST:"DROP_DOWN_LIST",
	ADD_INPUT_BOX:"ADD_INPUT_BOX",
	CHANGE_STATUS:"CHANGE_STATUS",
	INPUT_BIG_BOX:"INPUT_BIG_BOX",
	CHECK_BOX:"CHECK_BOX",
	MEDIA_BOX:"MEDIA_BOX",
	CALENDAR_BOX:"CALENDAR_BOX"
}