export const inputConstant={
	INPUT_SEARCH:"INPUT_SEARCH",
	INPUT_TEXT_BOX:"INPUT_TEXT_BOX",
	INPUT_NUMBER_BOX:"INPUT_NUMBER_BOX",
	DROP_DOWN_LIST:"DROP_DOWN_LIST",
	ADD_INPUT_BOX:"ADD_INPUT_BOX",
	CHANGE_STATUS:"CHANGE_STATUS",
	CURRENT_INPUT:"CURRENT_INPUT"
}