export const messageConstant={
	MESSAGE_INFORMATION:"MESSAGE_INFORMATION",
	MESSAGE_SUCCESSFULY:"MESSAGE_SUCCESSFULY",
	MESSAGE_ERRO:"MESSAGE_ERRO",
	BUTTON_CLOSE:"BUTTON_CLOSE",
	msgAutheticatedFalse:'Vui lòng đăng nhập'
}
