export const modeNews={
	NEWS_ALL:"NEWS_ALL",
	NEWS_WAIT_PAYMENT:'NEWS_WAIT_PAYMENT',
	WAITING_APROVED:"WAITING_APROVED",
	NEWS_REJECT:"NEWS_REJECT",
	WAITING_SHOW:"WAITING_SHOW",
	SHOWING:"SHOWING",
	HINDDEN:"HINDDEN",
	EXPRIED:"EXPRIED"
}